### ISSUE TITLE
Remove opacity slider for certain layers & Slider moves map

### ISSUE THREAD

**Issue by HugoP27** [GreenInfo-Network/L.Control.AccordionLegend#16]
Hi

1. Is it possible to remove the slider for some layers? 

2. When I use the slider it moves the map as well, please see attached zip file, how can I fix this?

Great plugin, thank you!

[Slider Demo.zip](https://github.com/GreenInfo-Network/L.Control.AccordionLegend/files/5629591/Slider.Demo.zip)

**Comment by gregallensworth** [comment]
Opacity sliders:    See release 1.2.4 which adds the `opacityslider` option to each layer. You can also see the new demo in `index.html` which demonstrates this.

Slider moves the map: This shouldn't happen with modern Leaflet, and does not happen in the demo using Leaflet 1.7  Some older Leaflet versions had a different way of stopping event propagation, so if you're using older than 1.4 or so that could be your problem.

**Comment by HugoP27** [comment]
Thanks a lot Greg!
